return { 
	'nvim-mini/mini.nvim', 
	version = false, 
	config = function() 
      local pick = require("plugins.config.pick")
      local clue = require("plugins.config.clue")
		require('mini.ai').setup()
		require('mini.align').setup()
		-- require('mini.animate').setup()
		require('mini.bracketed').setup()
		require('mini.clue').setup(clue)
		require('mini.diff').setup()
		require('mini.files').setup()
		require('mini.git').setup()
		require('mini.indentscope').setup()
		require('mini.icons').setup()
		require('mini.move').setup()
		require('mini.pairs').setup()
		require('mini.pick').setup(pick)
		require('mini.sessions').setup()
		require('mini.splitjoin').setup()
		require('mini.starter').setup()
		require('mini.statusline').setup()
		require('mini.surround').setup()
		require('mini.visits').setup()
	end }
